#!/usr/bin/env node
/**
 * يولّد ملفات الرموز للويب والجوال من tokens.json ويتحقق من تباين الألوان.
 * Generates web CSS + Flutter Dart from tokens.json and enforces WCAG AA contrast.
 *
 *   node packages/design-tokens/build.mjs          # write outputs
 *   node packages/design-tokens/build.mjs --check  # CI: fail if outputs are stale or contrast fails
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const tokens = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));
const OUT_CSS = join(root, 'apps/web/src/styles/tokens.css');
const OUT_DART = join(root, 'apps/mobile/lib/core/theme/app_tokens.dart');
const HEADER = 'GENERATED by packages/design-tokens/build.mjs from tokens.json — do not edit by hand.';

const resolve = (value) => {
  if (value.startsWith('#')) return value;
  const [group, shade] = value.split('.');
  const hex = tokens.palette[group]?.[shade];
  if (!hex) throw new Error(`Unknown color reference ${value}`);
  return hex;
};
const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
// CSS/Tailwind names read well as utilities: text-fg-muted, bg-canvas, border-line…
const CSS_NAMES = { background: 'canvas', text: 'fg', textMuted: 'fg-muted', textSubtle: 'fg-subtle', border: 'line', borderStrong: 'line-strong' };
const cssName = (k) => CSS_NAMES[k] ?? kebab(k);
const modes = ['light', 'dark'];
const semantic = Object.fromEntries(
  modes.map((m) => [m, Object.fromEntries(Object.entries(tokens.semantic[m]).map(([k, v]) => [k, resolve(v)]))]),
);

// ── WCAG contrast ─────────────────────────────────────────────
const luminance = (hex) => {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
    .map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
const ratio = (a, b) => {
  const [l1, l2] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (l1 + 0.05) / (l2 + 0.05);
};
const failures = [];
for (const mode of modes) {
  for (const [fg, bg] of tokens.contrast.pairs) {
    const r = ratio(semantic[mode][fg], semantic[mode][bg]);
    if (r < 4.5) failures.push(`${mode}: ${fg} on ${bg} = ${r.toFixed(2)}:1 (needs 4.5:1)`);
  }
}

// ── Web (Tailwind v4 + CSS variables) ─────────────────────────
const vars = (mode) =>
  [
    ...Object.entries(mode === 'light' ? tokens.palette.gray : tokens.palette.grayDark).map(
      ([k, v]) => `  --ds-gray-${k}: ${v};`,
    ),
    ...Object.entries(semantic[mode]).map(([k, v]) => `  --ds-${cssName(k)}: ${v};`),
    `  color-scheme: ${mode};`,
  ].join('\n');

const css = `/* ${HEADER} */

/*
 * Tailwind utilities read these theme variables. Gray and the semantic colors point at
 * runtime variables that swap in dark mode, so existing classes (bg-gray-50, text-gray-900…)
 * and the semantic ones (bg-surface, text-muted, bg-primary…) follow the theme automatically.
 */
@theme {
  --font-sans: var(--font-cairo), var(--font-inter), system-ui, sans-serif;
${Object.entries(tokens.palette.brand).map(([k, v]) => `  --color-brand-${k}: ${v};`).join('\n')}
${Object.entries(tokens.palette.accent).map(([k, v]) => `  --color-accent-${k}: ${v};`).join('\n')}
${Object.keys(tokens.palette.gray).map((k) => `  --color-gray-${k}: var(--ds-gray-${k});`).join('\n')}
${Object.keys(tokens.semantic.light).map((k) => `  --color-${cssName(k)}: var(--ds-${cssName(k)});`).join('\n')}
${Object.entries(tokens.radius).map(([k, v]) => `  --radius-${k}: ${v}px;`).join('\n')}
${Object.entries(tokens.shadow).map(([k, v]) => `  --shadow-${k}: ${v};`).join('\n')}
  --ease-standard: ${tokens.motion.easing};
}

:root {
${vars('light')}
}

/* Follows the OS setting unless the user picked a theme (data-theme on <html>). */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${vars('dark').replace(/^/gm, '  ')}
  }
}

:root[data-theme='dark'] {
${vars('dark')}
}
`;

// ── Flutter ───────────────────────────────────────────────────
const dartColor = (hex) => `Color(0xFF${hex.slice(1).toUpperCase()})`;
const constClass = (mode) => (mode === 'light' ? 'AppLightColors' : 'AppDarkColors');
const dartColors = (mode) =>
  Object.keys(semantic[mode]).map((k) => `    ${k}: ${constClass(mode)}.${k},`).join('\n');
const dartConsts = (mode) =>
  `/// Compile-time constants (usable inside \`const\` widgets).\nabstract final class ${constClass(mode)} {\n` +
  Object.entries(semantic[mode]).map(([k, v]) => `  static const ${k} = ${dartColor(v)};`).join('\n') +
  '\n}\n';
const dart = `// ${HEADER}
// ignore_for_file: constant_identifier_names
import 'package:flutter/material.dart';

/// Semantic colors for one theme mode. Use these instead of hard-coded colors.
@immutable
class AppColors {
${Object.keys(tokens.semantic.light).map((k) => `  final Color ${k};`).join('\n')}

  const AppColors({
${Object.keys(tokens.semantic.light).map((k) => `    required this.${k},`).join('\n')}
  });

  static const light = AppColors(
${dartColors('light')}
  );

  static const dark = AppColors(
${dartColors('dark')}
  );
}

${dartConsts('light')}
${dartConsts('dark')}
/// Brand palette (same in both modes).
abstract final class AppPalette {
${Object.entries(tokens.palette.brand).map(([k, v]) => `  static const brand${k} = ${dartColor(v)};`).join('\n')}
${Object.entries(tokens.palette.accent).map(([k, v]) => `  static const accent${k} = ${dartColor(v)};`).join('\n')}
}

/// Spacing scale in logical pixels (4px grid).
abstract final class AppSpace {
${Object.entries(tokens.space).map(([k, v]) => `  static const double s${k} = ${v};`).join('\n')}
}

abstract final class AppRadius {
${Object.entries(tokens.radius).map(([k, v]) => `  static const double ${k} = ${v};`).join('\n')}
}

abstract final class AppFontSize {
${Object.entries(tokens.font.size).map(([k, v]) => `  static const double ${/^\d/.test(k) ? `xl${k[0]}` : k} = ${v};`).join('\n')}
}

abstract final class AppMotion {
${['fast', 'normal', 'slow'].map((k) => `  static const ${k} = Duration(milliseconds: ${tokens.motion[k]});`).join('\n')}
}

const double kMinTouchTarget = ${tokens.touchTarget};
const String kFontFamily = '${tokens.font.family.sans}';
`;

// ── Write / check ─────────────────────────────────────────────
const check = process.argv.includes('--check');
let stale = [];
for (const [file, content] of [[OUT_CSS, css], [OUT_DART, dart]]) {
  if (check) {
    if (!existsSync(file) || readFileSync(file, 'utf8') !== content) stale.push(file);
  } else {
    writeFileSync(file, content);
    console.log(`wrote ${file.replace(root + '/', '')}`);
  }
}
if (failures.length) {
  console.error('Contrast failures (WCAG AA):\n  ' + failures.join('\n  '));
}
if (stale.length) {
  console.error('Generated files are stale, run: node packages/design-tokens/build.mjs\n  ' + stale.join('\n  '));
}
if (failures.length || stale.length) process.exit(1);
console.log(`contrast OK: ${tokens.contrast.pairs.length * modes.length} pairs meet WCAG AA`);
