// GENERATED by packages/design-tokens/build.mjs from tokens.json — do not edit by hand.
// ignore_for_file: constant_identifier_names
import 'package:flutter/material.dart';

/// Semantic colors for one theme mode. Use these instead of hard-coded colors.
@immutable
class AppColors {
  final Color background;
  final Color surface;
  final Color surfaceMuted;
  final Color border;
  final Color borderStrong;
  final Color text;
  final Color textMuted;
  final Color textSubtle;
  final Color primary;
  final Color primaryHover;
  final Color onPrimary;
  final Color primarySoft;
  final Color onPrimarySoft;
  final Color accent;
  final Color onAccent;
  final Color danger;
  final Color dangerSoft;
  final Color success;
  final Color successSoft;
  final Color warning;
  final Color warningSoft;
  final Color focusRing;

  const AppColors({
    required this.background,
    required this.surface,
    required this.surfaceMuted,
    required this.border,
    required this.borderStrong,
    required this.text,
    required this.textMuted,
    required this.textSubtle,
    required this.primary,
    required this.primaryHover,
    required this.onPrimary,
    required this.primarySoft,
    required this.onPrimarySoft,
    required this.accent,
    required this.onAccent,
    required this.danger,
    required this.dangerSoft,
    required this.success,
    required this.successSoft,
    required this.warning,
    required this.warningSoft,
    required this.focusRing,
  });

  static const light = AppColors(
    background: AppLightColors.background,
    surface: AppLightColors.surface,
    surfaceMuted: AppLightColors.surfaceMuted,
    border: AppLightColors.border,
    borderStrong: AppLightColors.borderStrong,
    text: AppLightColors.text,
    textMuted: AppLightColors.textMuted,
    textSubtle: AppLightColors.textSubtle,
    primary: AppLightColors.primary,
    primaryHover: AppLightColors.primaryHover,
    onPrimary: AppLightColors.onPrimary,
    primarySoft: AppLightColors.primarySoft,
    onPrimarySoft: AppLightColors.onPrimarySoft,
    accent: AppLightColors.accent,
    onAccent: AppLightColors.onAccent,
    danger: AppLightColors.danger,
    dangerSoft: AppLightColors.dangerSoft,
    success: AppLightColors.success,
    successSoft: AppLightColors.successSoft,
    warning: AppLightColors.warning,
    warningSoft: AppLightColors.warningSoft,
    focusRing: AppLightColors.focusRing,
  );

  static const dark = AppColors(
    background: AppDarkColors.background,
    surface: AppDarkColors.surface,
    surfaceMuted: AppDarkColors.surfaceMuted,
    border: AppDarkColors.border,
    borderStrong: AppDarkColors.borderStrong,
    text: AppDarkColors.text,
    textMuted: AppDarkColors.textMuted,
    textSubtle: AppDarkColors.textSubtle,
    primary: AppDarkColors.primary,
    primaryHover: AppDarkColors.primaryHover,
    onPrimary: AppDarkColors.onPrimary,
    primarySoft: AppDarkColors.primarySoft,
    onPrimarySoft: AppDarkColors.onPrimarySoft,
    accent: AppDarkColors.accent,
    onAccent: AppDarkColors.onAccent,
    danger: AppDarkColors.danger,
    dangerSoft: AppDarkColors.dangerSoft,
    success: AppDarkColors.success,
    successSoft: AppDarkColors.successSoft,
    warning: AppDarkColors.warning,
    warningSoft: AppDarkColors.warningSoft,
    focusRing: AppDarkColors.focusRing,
  );
}

/// Compile-time constants (usable inside `const` widgets).
abstract final class AppLightColors {
  static const background = Color(0xFFF8FAFC);
  static const surface = Color(0xFFFFFFFF);
  static const surfaceMuted = Color(0xFFF1F5F9);
  static const border = Color(0xFFE2E8F0);
  static const borderStrong = Color(0xFFCBD5E1);
  static const text = Color(0xFF0F172A);
  static const textMuted = Color(0xFF475569);
  static const textSubtle = Color(0xFF64748B);
  static const primary = Color(0xFF0F766E);
  static const primaryHover = Color(0xFF115E59);
  static const onPrimary = Color(0xFFFFFFFF);
  static const primarySoft = Color(0xFFF0FDFA);
  static const onPrimarySoft = Color(0xFF115E59);
  static const accent = Color(0xFFF59E0B);
  static const onAccent = Color(0xFF0F172A);
  static const danger = Color(0xFFB91C1C);
  static const dangerSoft = Color(0xFFFEF2F2);
  static const success = Color(0xFF15803D);
  static const successSoft = Color(0xFFF0FDF4);
  static const warning = Color(0xFFB45309);
  static const warningSoft = Color(0xFFFFFBEB);
  static const focusRing = Color(0xFF14B8A6);
}

/// Compile-time constants (usable inside `const` widgets).
abstract final class AppDarkColors {
  static const background = Color(0xFF0B1220);
  static const surface = Color(0xFF111A2B);
  static const surfaceMuted = Color(0xFF1E293B);
  static const border = Color(0xFF334155);
  static const borderStrong = Color(0xFF64748B);
  static const text = Color(0xFFF1F5F9);
  static const textMuted = Color(0xFFCBD5E1);
  static const textSubtle = Color(0xFF94A3B8);
  static const primary = Color(0xFF2DD4BF);
  static const primaryHover = Color(0xFF5EEAD4);
  static const onPrimary = Color(0xFF042F2E);
  static const primarySoft = Color(0xFF042F2E);
  static const onPrimarySoft = Color(0xFF99F6E4);
  static const accent = Color(0xFFFBBF24);
  static const onAccent = Color(0xFF0F172A);
  static const danger = Color(0xFFF87171);
  static const dangerSoft = Color(0xFF2A1215);
  static const success = Color(0xFF4ADE80);
  static const successSoft = Color(0xFF0F2A1A);
  static const warning = Color(0xFFFBBF24);
  static const warningSoft = Color(0xFF2A2110);
  static const focusRing = Color(0xFF2DD4BF);
}

/// Brand palette (same in both modes).
abstract final class AppPalette {
  static const brand50 = Color(0xFFF0FDFA);
  static const brand100 = Color(0xFFCCFBF1);
  static const brand200 = Color(0xFF99F6E4);
  static const brand300 = Color(0xFF5EEAD4);
  static const brand400 = Color(0xFF2DD4BF);
  static const brand500 = Color(0xFF14B8A6);
  static const brand600 = Color(0xFF0D9488);
  static const brand700 = Color(0xFF0F766E);
  static const brand800 = Color(0xFF115E59);
  static const brand900 = Color(0xFF134E4A);
  static const brand950 = Color(0xFF042F2E);
  static const accent100 = Color(0xFFFEF3C7);
  static const accent400 = Color(0xFFFBBF24);
  static const accent500 = Color(0xFFF59E0B);
  static const accent700 = Color(0xFFB45309);
  static const accent800 = Color(0xFF92400E);
}

/// Spacing scale in logical pixels (4px grid).
abstract final class AppSpace {
  static const double s0 = 0;
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  static const double s4 = 16;
  static const double s5 = 20;
  static const double s6 = 24;
  static const double s8 = 32;
  static const double s10 = 40;
  static const double s12 = 48;
  static const double s16 = 64;
}

abstract final class AppRadius {
  static const double control = 10;
  static const double card = 14;
  static const double sheet = 20;
  static const double pill = 9999;
}

abstract final class AppFontSize {
  static const double xs = 12;
  static const double sm = 14;
  static const double base = 16;
  static const double lg = 18;
  static const double xl = 20;
  static const double xl2 = 24;
  static const double xl3 = 30;
  static const double xl4 = 36;
}

abstract final class AppMotion {
  static const fast = Duration(milliseconds: 120);
  static const normal = Duration(milliseconds: 200);
  static const slow = Duration(milliseconds: 320);
}

const double kMinTouchTarget = 44;
const String kFontFamily = 'Cairo';
